name: Build and Run Services

on:
  push:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: self-hosted
    strategy:
      matrix:
        service: [foms, nginx]  # List of services to build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          username: "lakshanwanniarachchi"
          password: "p2hndb@12345"

      - name: Build and push foms
        if: ${{ matrix.service == 'foms' }}
        run: |
          docker build -t lakshanwanniarachchi/foms2:latest .
          docker push lakshanwanniarachchi/foms2:latest


      - name: Run service:foms
        if: ${{ matrix.service == 'foms' }}
        uses: addnab/docker-run-action@v3
        with:
          image: lakshanwanniarachchi/foms2:latest
          options: -d -p 5000:5000 -v /path/to/static:/website/templates

      - name: Build and push nginx
        if: ${{ matrix.service == 'nginx' }}
        run: |
          docker build -t lakshanwanniarachchi/nginx2:latest nginx
          docker push lakshanwanniarachchi/nginx2:latest

    

      - name: Run service:nginx
        if: ${{ matrix.service == 'nginx' }}
        uses: addnab/docker-run-action@v3
        with:
          image: lakshanwanniarachchi/nginx2:latest
          options: -d -p 80:80 -v /path/to/static:/website/templates
